volumes:
  eleni_postgres_data:

services:
  postgres:
    container_name: eleni_postgres
    image: postgres:17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - eleni_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped