volumes:
  eleni_postgres_data:

services:
  postgres:
    container_name: eleni_postgres
    image: postgres:17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - eleni_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  backend:
    container_name: eleni_bot_backend
    build: ./bot_backend/
    env_file: .env
    environment:
      DB_HOST: postgres
    volumes:
      - ./data:/data
      - ./media:/media
      - ./tarot:/tarot
    depends_on:
      - postgres
    restart: unless-stopped