volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres
    image: postgres:17
    env_file: .env
    environment:
      DB_HOST: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data