volumes:
  postgres_data:
  alembic_data:

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: bot_backend
    build: ./bot_backend/
    env_file: .env
    volumes:
      - alembic_data:/bot_backend/alembic/versions
    depends_on:
      - postgres
    restart: always