volumes:
  postgres_data:

services:
  postgres:
    container_name: postgres
    image: postgres:17
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: bot_backend
    build: ./bot_backend/
    env_file: .env
    volumes:
      - ./media:/media
      - ./tarot:/tarot
    depends_on:
      - postgres
    restart: always